const ACTION_TYPES = {

    //user login action keys 
    USER_NAME_CHANGED: 'USER_NAME',
    PASSWORD_CHANGED: 'PASSWORD_CHANGED',
    LOGIN_USER_RES: 'LOGIN_USER_RES',
    FETCHING_DATA: 'FETCHING_DATA',
    RESET_DATA: 'RESET_DATA',
    LOGIN_USER_RES_CLEAR: 'LOGIN_USER_RES_CLEAR',

    USER_NAME_CHANGED_CAR: 'USER_NAME_CHANGED_CAR',
    PASSWORD_CHANGED_CAR: 'PASSWORD_CHANGED_CAR',
    LOGIN_USER_RES_CAR: 'LOGIN_USER_RES_CAR',

}
export default ACTION_TYPES